class Constants {
  static const Map<String, List<String>> categoryGroups = {
    "Cybersecurity Fundamentals": [
      "Security Principles & Concepts",
      "Threat Landscape & Attack Vectors",
    ],
    "Penetration Testing": [
      "Reconnaissance & Information Gathering",
      "Vulnerability Assessment",
      "Exploitation Techniques",
    ],
    "Network Security": [
      "Network Attacks & Defense",
      "Wireless Security",
      "Network Protocols Security",
    ],
    "Web Application Security": [
      "Web Attacks & Vulnerabilities",
      "API Security",
      "Browser Security",
    ],
    "System & Host Security": [
      "Operating System Security",
      "Malware Analysis & Reverse Engineering",
      "Privilege Escalation",
    ],
    "Cryptography & Data Protection": [
      "Cryptographic Systems",
      "Authentication & Access Control",
    ],
    "Security Operations & Defense": [
      "Incident Response",
      "Forensics & Investigation",
      "Blue Teaming & Defense",
    ],
    "Social Engineering & Physical Security": [
      "Human Factors Security",
      "Physical Security Assessments",
    ],
    "Specialized Domains": [
      "Mobile Security",
      "Cloud Security",
      "IoT & OT Security",
    ],
    "Ethics & Legal Framework": [
      "Hacking Ethics & Professionalism",
      "Legal & Compliance",
    ],
  };

  static const Map<String, List<Map<String, dynamic>>> allTypes = {
    "Security Principles & Concepts": [
      {
        'id': 'security_fundamentals',
        'title': 'Security Fundamentals',
        'tier': 'free',
        'topics': [
          "CIA Triad",
          "Security Models",
          "Defense in Depth",
          "Zero Trust Architecture",
          "Security Governance",
        ],
      },
      {
        'id': 'threat_modeling',
        'title': 'Threat Modeling',
        'tier': 'free',
        'topics': [
          "STRIDE Methodology",
          "DREAD Scoring",
          "Attack Trees",
          "Data Flow Diagrams",
          "Risk Assessment",
        ],
      },
      {
        'id': 'security_controls',
        'title': 'Security Controls Framework',
        'tier': 'free',
        'topics': [
          "Preventive Controls",
          "Detective Controls",
          "Corrective Controls",
          "Compensating Controls",
          "NIST Cybersecurity Framework",
        ],
      },
      {
        'id': 'security_architecture',
        'title': 'Security Architecture',
        'tier': 'vip',
        'topics': [
          "Secure Design Principles",
          "Security Patterns",
          "Microsegmentation",
          "Perimeter Security",
          "Hybrid Security Models",
        ],
      },
    ],
    "Threat Landscape & Attack Vectors": [
      {
        'id': 'threat_intelligence',
        'title': 'Threat Intelligence',
        'tier': 'free',
        'topics': [
          "Threat Actors",
          "APT Groups",
          "TTPs (Tactics, Techniques, Procedures)",
          "Indicators of Compromise",
          "Threat Feeds",
        ],
      },
      {
        'id': 'attack_vectors',
        'title': 'Common Attack Vectors',
        'tier': 'free',
        'topics': [
          "Phishing Attacks",
          "Malware Delivery",
          "Supply Chain Attacks",
          "Insider Threats",
          "Zero-day Exploits",
        ],
      },
      {
        'id': 'vulnerability_types',
        'title': 'Vulnerability Types',
        'tier': 'free',
        'topics': [
          "Configuration Vulnerabilities",
          "Software Vulnerabilities",
          "Design Flaws",
          "Business Logic Vulnerabilities",
          "Human Vulnerabilities",
        ],
      },
      {
        'id': 'advanced_persistent_threats',
        'title': 'Advanced Persistent Threats',
        'tier': 'vip',
        'topics': [
          "APT Lifecycle",
          "Nation-State Actors",
          "Cyber Espionage",
          "Long-term Compromise",
          "Lateral Movement Techniques",
        ],
      },
    ],
    "Reconnaissance & Information Gathering": [
      {
        'id': 'passive_recon',
        'title': 'Passive Reconnaissance',
        'tier': 'free',
        'topics': [
          "WHOIS Lookups",
          "DNS Enumeration",
          "Search Engine Dorking",
          "Social Media Intelligence",
          "Public Records Analysis",
        ],
      },
      {
        'id': 'active_recon',
        'title': 'Active Reconnaissance',
        'tier': 'free',
        'topics': [
          "Port Scanning",
          "Service Fingerprinting",
          "Banner Grabbing",
          "Network Mapping",
          "DNS Zone Transfers",
        ],
      },
      {
        'id': 'osint',
        'title': 'OSINT Techniques',
        'tier': 'free',
        'topics': [
          "Email Harvesting",
          "Metadata Extraction",
          "Website Archiving",
          "Image Analysis",
          "Persona Development",
        ],
      },
      {
        'id': 'recon_tools',
        'title': 'Reconnaissance Tools',
        'tier': 'vip',
        'topics': [
          "Nmap Advanced Scanning",
          "Maltego",
          "theHarvester",
          "Recon-ng",
          "Shodan & Censys",
        ],
      },
    ],
    "Vulnerability Assessment": [
      {
        'id': 'vuln_scanning',
        'title': 'Vulnerability Scanning',
        'tier': 'free',
        'topics': [
          "Scanner Types",
          "Credentialed vs Non-Credentialed",
          "False Positives Management",
          "Risk Scoring",
          "Scan Scheduling",
        ],
      },
      {
        'id': 'web_vuln_assessment',
        'title': 'Web Vulnerability Assessment',
        'tier': 'free',
        'topics': [
          "Automated Scanners",
          "Manual Testing Techniques",
          "Input Validation Testing",
          "Session Management Testing",
          "Configuration Review",
        ],
      },
      {
        'id': 'network_vuln_assessment',
        'title': 'Network Vulnerability Assessment',
        'tier': 'free',
        'topics': [
          "Service Vulnerabilities",
          "Protocol Weaknesses",
          "Configuration Audits",
          "Wireless Assessments",
          "Device Hardening Checks",
        ],
      },
      {
        'id': 'advanced_vuln_assessment',
        'title': 'Advanced Assessment Techniques',
        'tier': 'vip',
        'topics': [
          "Fuzzing Techniques",
          "Code Review",
          "Binary Analysis",
          "Threat Hunting",
          "Red Team Exercises",
        ],
      },
    ],
    "Exploitation Techniques": [
      {
        'id': 'exploit_development',
        'title': 'Exploit Development Basics',
        'tier': 'free',
        'topics': [
          "Buffer Overflows",
          "Format String Vulnerabilities",
          "Integer Overflows",
          "Memory Corruption",
          "Shellcode Development",
        ],
      },
      {
        'id': 'web_exploitation',
        'title': 'Web Exploitation',
        'tier': 'free',
        'topics': [
          "SQL Injection",
          "Cross-Site Scripting",
          "Command Injection",
          "File Inclusion",
          "XXE Attacks",
        ],
      },
      {
        'id': 'post_exploitation',
        'title': 'Post-Exploitation',
        'tier': 'free',
        'topics': [
          "Persistence Mechanisms",
          "Lateral Movement",
          "Privilege Escalation",
          "Data Exfiltration",
          "Covering Tracks",
        ],
      },
      {
        'id': 'advanced_exploitation',
        'title': 'Advanced Exploitation',
        'tier': 'vip',
        'topics': [
          "ROP Chains",
          "Heap Exploitation",
          "Kernel Exploits",
          "Browser Exploitation",
          "Mobile Exploitation",
        ],
      },
    ],
    "Network Attacks & Defense": [
      {
        'id': 'network_attacks',
        'title': 'Network-Based Attacks',
        'tier': 'free',
        'topics': [
          "Man-in-the-Middle",
          "ARP Spoofing",
          "DNS Spoofing",
          "DHCP Attacks",
          "VLAN Hopping",
        ],
      },
      {
        'id': 'dos_attacks',
        'title': 'Denial of Service Attacks',
        'tier': 'free',
        'topics': [
          "Volumetric Attacks",
          "Protocol Attacks",
          "Application Layer Attacks",
          "DDoS Mitigation",
          "Botnets",
        ],
      },
      {
        'id': 'network_defense',
        'title': 'Network Defense Mechanisms',
        'tier': 'free',
        'topics': [
          "Firewalls",
          "Intrusion Detection Systems",
          "Intrusion Prevention Systems",
          "Network Segmentation",
          "Honeypots",
        ],
      },
      {
        'id': 'advanced_network_security',
        'title': 'Advanced Network Security',
        'tier': 'vip',
        'topics': [
          "Network Traffic Analysis",
          "Full Packet Capture",
          "Encrypted Traffic Analysis",
          "SDN Security",
          "Zero Trust Networking",
        ],
      },
    ],
    "Wireless Security": [
      {
        'id': 'wifi_security',
        'title': 'WiFi Security',
        'tier': 'free',
        'topics': [
          "WEP/WPA/WPA2/WPA3",
          "Evil Twin Attacks",
          "Deauthentication Attacks",
          "KRACK Attack",
          "WiFi Pineapple",
        ],
      },
      {
        'id': 'bluetooth_security',
        'title': 'Bluetooth Security',
        'tier': 'free',
        'topics': [
          "Bluetooth Attacks",
          "BLE Security",
          "Pairing Mechanisms",
          "Bluejacking",
          "Bluesnarfing",
        ],
      },
      {
        'id': 'rfid_nfc',
        'title': 'RFID & NFC Security',
        'tier': 'free',
        'topics': [
          "RFID Cloning",
          "NFC Attacks",
          "Proximity Card Security",
          "Contactless Payment Security",
          "RFID Jamming",
        ],
      },
      {
        'id': 'wireless_defense',
        'title': 'Wireless Defense Strategies',
        'tier': 'vip',
        'topics': [
          "Wireless Intrusion Detection",
          "Rogue AP Detection",
          "Wireless Hardening",
          "Wireless Penetration Testing",
          "Wireless Security Monitoring",
        ],
      },
    ],
    "Network Protocols Security": [
      {
        'id': 'tcp_ip_security',
        'title': 'TCP/IP Security',
        'tier': 'free',
        'topics': [
          "IP Spoofing",
          "TCP Sequence Prediction",
          "SYN Floods",
          "TCP Session Hijacking",
          "IP Fragmentation Attacks",
        ],
      },
      {
        'id': 'dns_security',
        'title': 'DNS Security',
        'tier': 'free',
        'topics': [
          "DNS Cache Poisoning",
          "DNSSEC",
          "DNS Tunneling",
          "DNS Amplification",
          "DNS Monitoring",
        ],
      },
      {
        'id': 'http_https',
        'title': 'HTTP/HTTPS Security',
        'tier': 'free',
        'topics': [
          "HTTPS Interception",
          "SSL/TLS Vulnerabilities",
          "HSTS",
          "HTTP/2 Security",
          "WebSocket Security",
        ],
      },
      {
        'id': 'voip_security',
        'title': 'VoIP & SIP Security',
        'tier': 'vip',
        'topics': [
          "SIP Vulnerabilities",
          "VoIP Eavesdropping",
          "Call Spoofing",
          "VoIP Denial of Service",
          "VoIP Security Best Practices",
        ],
      },
    ],
    "Web Attacks & Vulnerabilities": [
      {
        'id': 'owasp_top10',
        'title': 'OWASP Top 10',
        'tier': 'free',
        'topics': [
          "Injection Flaws",
          "Broken Authentication",
          "Sensitive Data Exposure",
          "XXE",
          "Broken Access Control",
          "Security Misconfiguration",
          "XSS",
          "Insecure Deserialization",
          "Using Components with Known Vulnerabilities",
          "Insufficient Logging & Monitoring",
        ],
      },
      {
        'id': 'client_side_attacks',
        'title': 'Client-Side Attacks',
        'tier': 'free',
        'topics': [
          "Cross-Site Request Forgery",
          "Clickjacking",
          "DOM-based XSS",
          "HTML Injection",
          "Client-Side Storage Attacks",
        ],
      },
      {
        'id': 'server_side_attacks',
        'title': 'Server-Side Attacks',
        'tier': 'free',
        'topics': [
          "Server-Side Request Forgery",
          "Remote Code Execution",
          "File Upload Vulnerabilities",
          "Path Traversal",
          "Insecure Direct Object References",
        ],
      },
      {
        'id': 'advanced_web_attacks',
        'title': 'Advanced Web Attacks',
        'tier': 'vip',
        'topics': [
          "Web Cache Poisoning",
          "HTTP Request Smuggling",
          "Prototype Pollution",
          "GraphQL Vulnerabilities",
          "WebAssembly Security",
        ],
      },
    ],
    "API Security": [
      {
        'id': 'rest_api_security',
        'title': 'REST API Security',
        'tier': 'free',
        'topics': [
          "API Authentication",
          "API Authorization",
          "Rate Limiting",
          "Input Validation",
          "Error Handling Security",
        ],
      },
      {
        'id': 'graphql_security',
        'title': 'GraphQL Security',
        'tier': 'free',
        'topics': [
          "GraphQL Introspection",
          "Query Depth Attacks",
          "Field Duplication",
          "Batching Attacks",
          "GraphQL Injection",
        ],
      },
      {
        'id': 'api_abuse',
        'title': 'API Abuse Techniques',
        'tier': 'free',
        'topics': [
          "Parameter Pollution",
          "Mass Assignment",
          "Business Logic Bypass",
          "Data Exposure",
          "Function Level Access Control",
        ],
      },
      {
        'id': 'api_testing',
        'title': 'API Security Testing',
        'tier': 'vip',
        'topics': [
          "API Fuzzing",
          "Swagger/OpenAPI Analysis",
          "JWT Security Testing",
          "OAuth Implementation Testing",
          "API Security Headers",
        ],
      },
    ],
    "Browser Security": [
      {
        'id': 'browser_vulnerabilities',
        'title': 'Browser Vulnerabilities',
        'tier': 'free',
        'topics': [
          "Same-Origin Policy",
          "Cross-Origin Resource Sharing",
          "Content Security Policy",
          "Browser Storage Security",
          "Web Workers Security",
        ],
      },
      {
        'id': 'extension_security',
        'title': 'Browser Extension Security',
        'tier': 'free',
        'topics': [
          "Extension Permissions",
          "Malicious Extensions",
          "Extension Vulnerabilities",
          "Extension Analysis",
          "Secure Extension Development",
        ],
      },
      {
        'id': 'browser_exploitation',
        'title': 'Browser Exploitation',
        'tier': 'vip',
        'topics': [
          "Drive-by Downloads",
          "Browser Memory Corruption",
          "JIT Exploitation",
          "Sandbox Escapes",
          "Browser Exploit Kits",
        ],
      },
    ],
    "Operating System Security": [
      {
        'id': 'windows_security',
        'title': 'Windows Security',
        'tier': 'free',
        'topics': [
          "Windows Authentication",
          "Active Directory Security",
          "Windows Privileges",
          "Windows Defender",
          "Group Policy Security",
        ],
      },
      {
        'id': 'linux_security',
        'title': 'Linux Security',
        'tier': 'free',
        'topics': [
          "Linux Permissions",
          "SELinux/AppArmor",
          "Linux Hardening",
          "Package Management Security",
          "Linux Authentication",
        ],
      },
      {
        'id': 'macos_security',
        'title': 'macOS Security',
        'tier': 'free',
        'topics': [
          "Gatekeeper",
          "FileVault",
          "System Integrity Protection",
          "macOS Sandboxing",
          "macOS Permissions",
        ],
      },
      {
        'id': 'os_hardening',
        'title': 'OS Hardening Techniques',
        'tier': 'vip',
        'topics': [
          "Security Baselines",
          "Patch Management",
          "Logging Configuration",
          "Kernel Security",
          "Container Security",
        ],
      },
    ],
    "Malware Analysis & Reverse Engineering": [
      {
        'id': 'malware_types',
        'title': 'Malware Types',
        'tier': 'free',
        'topics': [
          "Viruses",
          "Worms",
          "Trojans",
          "Ransomware",
          "Spyware",
          "Rootkits",
          "Botnets",
        ],
      },
      {
        'id': 'static_analysis',
        'title': 'Static Analysis',
        'tier': 'free',
        'topics': [
          "File Hashing",
          "Strings Analysis",
          "PE File Analysis",
          "Disassembly",
          "Import/Export Analysis",
        ],
      },
      {
        'id': 'dynamic_analysis',
        'title': 'Dynamic Analysis',
        'tier': 'free',
        'topics': [
          "Sandbox Analysis",
          "Behavior Monitoring",
          "Network Traffic Analysis",
          "API Hooking",
          "Memory Dumping",
        ],
      },
      {
        'id': 'reverse_engineering',
        'title': 'Reverse Engineering',
        'tier': 'vip',
        'topics': [
          "IDA Pro/Ghidra",
          "Debugging Techniques",
          "Obfuscation Analysis",
          "Packing/Unpacking",
          "Firmware Reverse Engineering",
        ],
      },
    ],
    "Privilege Escalation": [
      {
        'id': 'windows_priv_esc',
        'title': 'Windows Privilege Escalation',
        'tier': 'free',
        'topics': [
          "Service Misconfigurations",
          "AlwaysInstallElevated",
          "Token Manipulation",
          "Unquoted Service Paths",
          "DLL Hijacking",
        ],
      },
      {
        'id': 'linux_priv_esc',
        'title': 'Linux Privilege Escalation',
        'tier': 'free',
        'topics': [
          "SUID/SGID Binaries",
          "Capabilities",
          "Cron Jobs",
          "NFS Misconfigurations",
          "Kernel Exploits",
        ],
      },
      {
        'id': 'macos_priv_esc',
        'title': 'macOS Privilege Escalation',
        'tier': 'free',
        'topics': [
          "Authorization Bypass",
          "Plists Misconfigurations",
          "Keychain Attacks",
          "LaunchDaemons/Agents",
          "macOS Kernel Exploits",
        ],
      },
      {
        'id': 'advanced_priv_esc',
        'title': 'Advanced Privilege Escalation',
        'tier': 'vip',
        'topics': [
          "Container Escape",
          "Hypervisor Escape",
          "Active Directory Privilege Escalation",
          "Cloud IAM Privilege Escalation",
          "Zero-day Privilege Escalation",
        ],
      },
    ],
    "Cryptographic Systems": [
      {
        'id': 'crypto_fundamentals',
        'title': 'Cryptography Fundamentals',
        'tier': 'free',
        'topics': [
          "Symmetric Encryption",
          "Asymmetric Encryption",
          "Hash Functions",
          "Digital Signatures",
          "Key Exchange Protocols",
        ],
      },
      {
        'id': 'crypto_attacks',
        'title': 'Cryptographic Attacks',
        'tier': 'free',
        'topics': [
          "Brute Force",
          "Dictionary Attacks",
          "Rainbow Tables",
          "Padding Oracle",
          "Side-Channel Attacks",
        ],
      },
      {
        'id': 'tls_ssl',
        'title': 'TLS/SSL Security',
        'tier': 'free',
        'topics': [
          "Certificate Validation",
          "Cipher Suite Selection",
          "Protocol Vulnerabilities",
          "Certificate Transparency",
          "HSTS Implementation",
        ],
      },
      {
        'id': 'crypto_implementation',
        'title': 'Cryptographic Implementation',
        'tier': 'vip',
        'topics': [
          "Cryptographic Libraries",
          "Random Number Generation",
          "Key Management",
          "Hardware Security Modules",
          "Post-Quantum Cryptography",
        ],
      },
    ],
    "Authentication & Access Control": [
      {
        'id': 'auth_methods',
        'title': 'Authentication Methods',
        'tier': 'free',
        'topics': [
          "Password Authentication",
          "Multi-Factor Authentication",
          "Biometric Authentication",
          "Certificate-based Authentication",
          "SSO Implementations",
        ],
      },
      {
        'id': 'access_control_models',
        'title': 'Access Control Models',
        'tier': 'free',
        'topics': [
          "DAC (Discretionary Access Control)",
          "MAC (Mandatory Access Control)",
          "RBAC (Role-Based Access Control)",
          "ABAC (Attribute-Based Access Control)",
          "PBAC (Policy-Based Access Control)",
        ],
      },
      {
        'id': 'auth_bypass',
        'title': 'Authentication Bypass',
        'tier': 'free',
        'topics': [
          "Password Attacks",
          "Session Hijacking",
          "Token Manipulation",
          "Credential Stuffing",
          "Password Spraying",
        ],
      },
      {
        'id': 'advanced_auth',
        'title': 'Advanced Authentication Security',
        'tier': 'vip',
        'topics': [
          "OAuth/OIDC Security",
          "SAML Security",
          "FIDO/WebAuthn",
          "Passwordless Authentication",
          "Zero-Knowledge Proofs",
        ],
      },
    ],
    "Incident Response": [
      {
        'id': 'ir_framework',
        'title': 'Incident Response Framework',
        'tier': 'free',
        'topics': [
          "NIST Incident Response Lifecycle",
          "Preparation Phase",
          "Detection & Analysis",
          "Containment, Eradication & Recovery",
          "Post-Incident Activity",
        ],
      },
      {
        'id': 'ir_tools',
        'title': 'Incident Response Tools',
        'tier': 'free',
        'topics': [
          "SIEM Systems",
          "EDR Solutions",
          "Network Monitoring",
          "Forensic Tools",
          "Incident Management Platforms",
        ],
      },
      {
        'id': 'ir_playbooks',
        'title': 'Incident Response Playbooks',
        'tier': 'free',
        'topics': [
          "Ransomware Response",
          "Data Breach Response",
          "DDoS Response",
          "Insider Threat Response",
          "Advanced Threat Response",
        ],
      },
      {
        'id': 'advanced_ir',
        'title': 'Advanced Incident Response',
        'tier': 'vip',
        'topics': [
          "Threat Hunting",
          "Digital Forensics Integration",
          "Malware Analysis Integration",
          "Cloud Incident Response",
          "ICS/SCADA Incident Response",
        ],
      },
    ],
    "Forensics & Investigation": [
      {
        'id': 'digital_forensics',
        'title': 'Digital Forensics',
        'tier': 'free',
        'topics': [
          "Disk Forensics",
          "Memory Forensics",
          "Network Forensics",
          "Mobile Forensics",
          "Cloud Forensics",
        ],
      },
      {
        'id': 'forensic_tools',
        'title': 'Forensic Tools',
        'tier': 'free',
        'topics': [
          "FTK",
          "Autopsy",
          "Volatility",
          "Wireshark Forensics",
          "EnCase",
        ],
      },
      {
        'id': 'evidence_handling',
        'title': 'Evidence Handling',
        'tier': 'free',
        'topics': [
          "Chain of Custody",
          "Legal Considerations",
          "Evidence Preservation",
          "Forensic Imaging",
          "Report Writing",
        ],
      },
      {
        'id': 'advanced_forensics',
        'title': 'Advanced Forensics',
        'tier': 'vip',
        'topics': [
          "Anti-Forensics Techniques",
          "Steganography Detection",
          "Encrypted Data Recovery",
          "IoT Forensics",
          "Vehicle Forensics",
        ],
      },
    ],
    "Blue Teaming & Defense": [
      {
        'id': 'security_monitoring',
        'title': 'Security Monitoring',
        'tier': 'free',
        'topics': [
          "Log Management",
          "Security Analytics",
          "Threat Detection",
          "Alert Tuning",
          "Dashboard Development",
        ],
      },
      {
        'id': 'defensive_tools',
        'title': 'Defensive Tools',
        'tier': 'free',
        'topics': [
          "Firewall Configuration",
          "IDS/IPS Tuning",
          "Antivirus Management",
          "Application Whitelisting",
          "Network Access Control",
        ],
      },
      {
        'id': 'defense_strategies',
        'title': 'Defense Strategies',
        'tier': 'free',
        'topics': [
          "Deception Technology",
          "Threat Intelligence Integration",
          "Security Automation",
          "Vulnerability Management",
          "Patch Management",
        ],
      },
      {
        'id': 'advanced_defense',
        'title': 'Advanced Defense Techniques',
        'tier': 'vip',
        'topics': [
          "Purple Teaming",
          "Threat Hunting",
          "Security Orchestration",
          "AI in Cybersecurity Defense",
          "Zero Trust Implementation",
        ],
      },
    ],
    "Human Factors Security": [
      {
        'id': 'social_engineering',
        'title': 'Social Engineering Techniques',
        'tier': 'free',
        'topics': [
          "Phishing",
          "Vishing",
          "Smishing",
          "Pretexting",
          "Baiting",
          "Quid Pro Quo",
          "Tailgating",
        ],
      },
      {
        'id': 'phishing_analysis',
        'title': 'Phishing Analysis',
        'tier': 'free',
        'topics': [
          "Email Header Analysis",
          "URL Analysis",
          "Attachment Analysis",
          "Brand Impersonation",
          "Psychological Triggers",
        ],
      },
      {
        'id': 'awareness_training',
        'title': 'Security Awareness Training',
        'tier': 'free',
        'topics': [
          "Training Program Development",
          "Phishing Simulations",
          "Behavior Change Metrics",
          "Gamification",
          "Continuous Learning",
        ],
      },
      {
        'id': 'advanced_social_engineering',
        'title': 'Advanced Social Engineering',
        'tier': 'vip',
        'topics': [
          "OSINT for Social Engineering",
          "Physical Social Engineering",
          "Watering Hole Attacks",
          "Supply Chain Social Engineering",
          "Executive Protection",
        ],
      },
    ],
    "Physical Security Assessments": [
      {
        'id': 'physical_security',
        'title': 'Physical Security Controls',
        'tier': 'free',
        'topics': [
          "Access Control Systems",
          "Surveillance Systems",
          "Alarm Systems",
          "Physical Barriers",
          "Security Personnel",
        ],
      },
      {
        'id': 'physical_pen_testing',
        'title': 'Physical Penetration Testing',
        'tier': 'free',
        'topics': [
          "Site Surveying",
          "Lock Picking",
          "Badge Cloning",
          "Tailgating Techniques",
          "Social Engineering Physical",
        ],
      },
      {
        'id': 'device_security',
        'title': 'Physical Device Security',
        'tier': 'free',
        'topics': [
          "USB Security",
          "Hard Drive Security",
          "Network Jack Security",
          "Server Room Security",
          "Mobile Device Physical Security",
        ],
      },
      {
        'id': 'advanced_physical_security',
        'title': 'Advanced Physical Security',
        'tier': 'vip',
        'topics': [
          "Red Team Physical Operations",
          "RFID Security Assessment",
          "Biometric System Bypass",
          "Secure Facility Design",
          "Convergence of Physical & Cyber",
        ],
      },
    ],
    "Mobile Security": [
      {
        'id': 'android_security',
        'title': 'Android Security',
        'tier': 'free',
        'topics': [
          "Android Architecture Security",
          "App Permissions",
          "Intent Security",
          "Root Detection",
          "Android Keystore",
        ],
      },
      {
        'id': 'ios_security',
        'title': 'iOS Security',
        'tier': 'free',
        'topics': [
          "iOS Sandbox",
          "Code Signing",
          "Data Protection API",
          "Jailbreak Detection",
          "Touch ID/Face ID Security",
        ],
      },
      {
        'id': 'mobile_app_testing',
        'title': 'Mobile App Security Testing',
        'tier': 'free',
        'topics': [
          "Static Analysis",
          "Dynamic Analysis",
          "Reverse Engineering",
          "Network Traffic Analysis",
          "Storage Analysis",
        ],
      },
      {
        'id': 'advanced_mobile_security',
        'title': 'Advanced Mobile Security',
        'tier': 'vip',
        'topics': [
          "Mobile Malware Analysis",
          "Mobile Device Management Security",
          "BYOD Security",
          "Mobile Payment Security",
          "5G Security Considerations",
        ],
      },
    ],
    "Cloud Security": [
      {
        'id': 'aws_security',
        'title': 'AWS Security',
        'tier': 'free',
        'topics': [
          "IAM Security",
          "S3 Security",
          "VPC Security",
          "CloudTrail",
          "Security Groups & NACLs",
        ],
      },
      {
        'id': 'azure_security',
        'title': 'Azure Security',
        'tier': 'free',
        'topics': [
          "Azure AD Security",
          "Storage Account Security",
          "Network Security Groups",
          "Azure Policy",
          "Key Vault Security",
        ],
      },
      {
        'id': 'gcp_security',
        'title': 'GCP Security',
        'tier': 'free',
        'topics': [
          "Cloud IAM",
          "Storage Security",
          "VPC Security",
          "Cloud Audit Logs",
          "Secret Manager",
        ],
      },
      {
        'id': 'cloud_pen_testing',
        'title': 'Cloud Penetration Testing',
        'tier': 'vip',
        'topics': [
          "Cloud Misconfigurations",
          "Container Security",
          "Serverless Security",
          "Cloud Forensics",
          "Multi-cloud Security",
        ],
      },
    ],
    "IoT & OT Security": [
      {
        'id': 'iot_security',
        'title': 'IoT Security',
        'tier': 'free',
        'topics': [
          "IoT Architecture Security",
          "Firmware Security",
          "IoT Communication Protocols",
          "IoT Device Hardening",
          "IoT Cloud Security",
        ],
      },
      {
        'id': 'ot_security',
        'title': 'OT/ICS Security',
        'tier': 'free',
        'topics': [
          "ICS Architecture",
          "PLC Security",
          "SCADA Security",
          "Industrial Protocols",
          "OT Network Segmentation",
        ],
      },
      {
        'id': 'embedded_security',
        'title': 'Embedded Systems Security',
        'tier': 'free',
        'topics': [
          "Hardware Security",
          "Firmware Analysis",
          "Side-Channel Attacks",
          "JTAG/UART Security",
          "Secure Boot",
        ],
      },
      {
        'id': 'advanced_iot_ot',
        'title': 'Advanced IoT/OT Security',
        'tier': 'vip',
        'topics': [
          "IoT Penetration Testing",
          "OT Penetration Testing",
          "Supply Chain Security",
          "Critical Infrastructure Protection",
          "Smart City Security",
        ],
      },
    ],
    "Hacking Ethics & Professionalism": [
      {
        'id': 'ethical_framework',
        'title': 'Ethical Framework',
        'tier': 'free',
        'topics': [
          "White Hat vs Black Hat",
          "Ethical Hacking Principles",
          "Professional Conduct",
          "Client Confidentiality",
          "Responsible Disclosure",
        ],
      },
      {
        'id': 'certifications',
        'title': 'Security Certifications',
        'tier': 'free',
        'topics': [
          "CEH",
          "OSCP",
          "CISSP",
          "CompTIA Security+",
          "GIAC Certifications",
          "Cloud Security Certifications",
        ],
      },
      {
        'id': 'career_paths',
        'title': 'Cybersecurity Career Paths',
        'tier': 'free',
        'topics': [
          "Penetration Tester",
          "Security Analyst",
          "Security Engineer",
          "Security Architect",
          "CISO",
          "Security Consultant",
        ],
      },
      {
        'id': 'professional_development',
        'title': 'Professional Development',
        'tier': 'vip',
        'topics': [
          "Continuing Education",
          "Conference Participation",
          "Research Publication",
          "Community Involvement",
          "Mentorship",
        ],
      },
    ],
    "Legal & Compliance": [
      {
        'id': 'cyber_laws',
        'title': 'Cybersecurity Laws',
        'tier': 'free',
        'topics': [
          "Computer Fraud and Abuse Act",
          "GDPR",
          "HIPAA",
          "PCI DSS",
          "SOX",
          "CCPA",
        ],
      },
      {
        'id': 'compliance_frameworks',
        'title': 'Compliance Frameworks',
        'tier': 'free',
        'topics': [
          "ISO 27001",
          "NIST CSF",
          "CIS Controls",
          "SOC 2",
          "FedRAMP",
          "MITRE ATT&CK",
        ],
      },
      {
        'id': 'contractual_considerations',
        'title': 'Contractual Considerations',
        'tier': 'free',
        'topics': [
          "Scope of Work",
          "Rules of Engagement",
          "Liability Limitations",
          "Insurance Requirements",
          "Non-Disclosure Agreements",
        ],
      },
      {
        'id': 'international_law',
        'title': 'International Cyber Law',
        'tier': 'vip',
        'topics': [
          "Cross-border Data Transfer",
          "International Investigations",
          "Cyber Warfare Law",
          "Digital Sovereignty",
          "International Compliance",
        ],
      },
    ],
  };
}
